# Auto-generated by scripts/generate_bids_tools.py — DO NOT EDIT
# Regenerate with: uv run scripts/generate_bids_tools.py
"""BIDS schema constants and utilities.

Auto-generated from BIDS schema v1.11.1.
Regenerate with: ``uv run scripts/generate_bids_tools.py``
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import PurePath
from typing import Literal

BIDS_VERSION = "1.11.1"

_LABEL_RE = re.compile(r"^[0-9a-zA-Z+]+$")

_COMPOUND_EXTENSIONS: tuple[str, ...] = (
    ".dlabel.nii",
    ".label.gii",
    ".ome.zarr/",
    ".ome.btf",
    ".ome.tif",
    ".nii.gz",
    ".tsv.gz",
)


class Datatype:
    """BIDS datatypes."""

    ANAT: Literal["anat"] = "anat"
    """Anatomical Magnetic Resonance Imaging."""

    BEH: Literal["beh"] = "beh"
    """Behavioral Data."""

    DWI: Literal["dwi"] = "dwi"
    """Diffusion-Weighted Imaging."""

    EEG: Literal["eeg"] = "eeg"
    """Electroencephalography."""

    EMG: Literal["emg"] = "emg"
    """Electromyography."""

    FMAP: Literal["fmap"] = "fmap"
    """Field maps."""

    FUNC: Literal["func"] = "func"
    """Task-Based Magnetic Resonance Imaging."""

    IEEG: Literal["ieeg"] = "ieeg"
    """Intracranial electroencephalography."""

    MEG: Literal["meg"] = "meg"
    """Magnetoencephalography."""

    MICR: Literal["micr"] = "micr"
    """Microscopy."""

    MOTION: Literal["motion"] = "motion"
    """Motion."""

    MRS: Literal["mrs"] = "mrs"
    """Magnetic Resonance Spectroscopy."""

    NIRS: Literal["nirs"] = "nirs"
    """Near-Infrared Spectroscopy."""

    PERF: Literal["perf"] = "perf"
    """Perfusion imaging."""

    PET: Literal["pet"] = "pet"
    """Positron Emission Tomography."""

    PHENOTYPE: Literal["phenotype"] = "phenotype"
    """Phenotype."""


class Suffix:
    """BIDS suffixes."""

    _2PE: Literal["2PE"] = "2PE"
    """2-photon excitation microscopy."""

    ADC: Literal["ADC"] = "ADC"
    """Apparent diffusion coefficient (ADC)."""

    BF: Literal["BF"] = "BF"
    """Bright-field microscopy."""

    CARS: Literal["CARS"] = "CARS"
    """Coherent anti-Stokes Raman spectroscopy."""

    CONF: Literal["CONF"] = "CONF"
    """Confocal microscopy."""

    CHIMAP: Literal["Chimap"] = "Chimap"
    """Quantitative susceptibility map (QSM)."""

    DF: Literal["DF"] = "DF"
    """Dark-field microscopy."""

    DIC: Literal["DIC"] = "DIC"
    """Differential interference contrast microscopy."""

    FA: Literal["FA"] = "FA"
    """Fractional Anisotropy image."""

    FLAIR: Literal["FLAIR"] = "FLAIR"
    """Fluid attenuated inversion recovery image."""

    FLASH: Literal["FLASH"] = "FLASH"
    """Fast-Low-Angle-Shot image."""

    FLUO: Literal["FLUO"] = "FLUO"
    """Fluorescence microscopy."""

    IRT1: Literal["IRT1"] = "IRT1"
    """Inversion recovery T1 mapping."""

    M0MAP: Literal["M0map"] = "M0map"
    """Equilibrium magnetization (M0) map."""

    MEGRE: Literal["MEGRE"] = "MEGRE"
    """Multi-echo Gradient Recalled Echo."""

    MESE: Literal["MESE"] = "MESE"
    """Multi-echo Spin Echo."""

    MP2RAGE: Literal["MP2RAGE"] = "MP2RAGE"
    """Magnetization Prepared Two Gradient Echoes."""

    MPE: Literal["MPE"] = "MPE"
    """Multi-photon excitation microscopy."""

    MPM: Literal["MPM"] = "MPM"
    """Multi-parametric Mapping."""

    MTR: Literal["MTR"] = "MTR"
    """Magnetization Transfer Ratio."""

    MTRMAP: Literal["MTRmap"] = "MTRmap"
    """Magnetization transfer ratio image."""

    MTS: Literal["MTS"] = "MTS"
    """Magnetization transfer saturation."""

    MTVMAP: Literal["MTVmap"] = "MTVmap"
    """Macromolecular tissue volume (MTV) image."""

    MTSAT: Literal["MTsat"] = "MTsat"
    """Magnetization transfer saturation image."""

    MWFMAP: Literal["MWFmap"] = "MWFmap"
    """Myelin water fraction image."""

    NLO: Literal["NLO"] = "NLO"
    """Nonlinear optical microscopy."""

    OCT: Literal["OCT"] = "OCT"
    """Optical coherence tomography."""

    PC: Literal["PC"] = "PC"
    """Phase-contrast microscopy."""

    PD: Literal["PD"] = "PD"
    """Proton density image."""

    PDT2: Literal["PDT2"] = "PDT2"
    """PD and T2 weighted image."""

    PDMAP: Literal["PDmap"] = "PDmap"
    """Proton density image."""

    PDW: Literal["PDw"] = "PDw"
    """Proton density (PD) weighted image."""

    PLI: Literal["PLI"] = "PLI"
    """Polarized-light microscopy."""

    R1MAP: Literal["R1map"] = "R1map"
    """Longitudinal relaxation rate image."""

    R2MAP: Literal["R2map"] = "R2map"
    """True transverse relaxation rate image."""

    R2STARMAP: Literal["R2starmap"] = "R2starmap"
    """Observed transverse relaxation rate image."""

    RB1COR: Literal["RB1COR"] = "RB1COR"
    """RB1COR."""

    RB1MAP: Literal["RB1map"] = "RB1map"
    """RF receive sensitivity map."""

    S0MAP: Literal["S0map"] = "S0map"
    """Projected baseline signal amplitude (S0) image."""

    SEM: Literal["SEM"] = "SEM"
    """Scanning electron microscopy."""

    SPIM: Literal["SPIM"] = "SPIM"
    """Selective plane illumination microscopy."""

    SR: Literal["SR"] = "SR"
    """Super-resolution microscopy."""

    T1MAP: Literal["T1map"] = "T1map"
    """Longitudinal relaxation time image."""

    T1RHO: Literal["T1rho"] = "T1rho"
    """T1 in rotating frame (T1 rho) image."""

    T1W: Literal["T1w"] = "T1w"
    """T1-weighted image."""

    T2MAP: Literal["T2map"] = "T2map"
    """True transverse relaxation time image."""

    T2STAR: Literal["T2star"] = "T2star"
    """T2* image."""

    T2STARMAP: Literal["T2starmap"] = "T2starmap"
    """Observed transverse relaxation time image."""

    T2STARW: Literal["T2starw"] = "T2starw"
    """T2star weighted image."""

    T2W: Literal["T2w"] = "T2w"
    """T2-weighted image."""

    TB1AFI: Literal["TB1AFI"] = "TB1AFI"
    """TB1AFI."""

    TB1DAM: Literal["TB1DAM"] = "TB1DAM"
    """TB1DAM."""

    TB1EPI: Literal["TB1EPI"] = "TB1EPI"
    """TB1EPI."""

    TB1RFM: Literal["TB1RFM"] = "TB1RFM"
    """TB1RFM."""

    TB1SRGE: Literal["TB1SRGE"] = "TB1SRGE"
    """TB1SRGE."""

    TB1TFL: Literal["TB1TFL"] = "TB1TFL"
    """TB1TFL."""

    TB1MAP: Literal["TB1map"] = "TB1map"
    """RF transmit field image."""

    TEM: Literal["TEM"] = "TEM"
    """Transmission electron microscopy."""

    UNIT1: Literal["UNIT1"] = "UNIT1"
    """Homogeneous (flat) T1-weighted MP2RAGE image."""

    VFA: Literal["VFA"] = "VFA"
    """Variable flip angle."""

    XPCT: Literal["XPCT"] = "XPCT"
    """X-ray Phase-Contrast Tomography."""

    ANGIO: Literal["angio"] = "angio"
    """Angiogram."""

    ASL: Literal["asl"] = "asl"
    """Arterial Spin Labeling."""

    ASLCONTEXT: Literal["aslcontext"] = "aslcontext"
    """Arterial Spin Labeling Context."""

    ASLLABELING: Literal["asllabeling"] = "asllabeling"
    """ASL Labeling Screenshot."""

    BEH: Literal["beh"] = "beh"
    """Behavioral recording."""

    BLOOD: Literal["blood"] = "blood"
    """Blood recording data."""

    BOLD: Literal["bold"] = "bold"
    """Blood-Oxygen-Level Dependent image."""

    CBV: Literal["cbv"] = "cbv"
    """Cerebral blood volume image."""

    CHANNELS: Literal["channels"] = "channels"
    """Channels File."""

    COLFA: Literal["colFA"] = "colFA"
    """Colored Fractional Anisotropy image."""

    COORDSYSTEM: Literal["coordsystem"] = "coordsystem"
    """Coordinate System File."""

    DEFACEMASK: Literal["defacemask"] = "defacemask"
    """Defacing Mask."""

    DESCRIPTION: Literal["description"] = "description"
    """Description file."""

    DESCRIPTIONS: Literal["descriptions"] = "descriptions"
    """Description Entity Definitions."""

    DSEG: Literal["dseg"] = "dseg"
    """Discrete Segmentation."""

    DWI: Literal["dwi"] = "dwi"
    """Diffusion-weighted image."""

    EEG: Literal["eeg"] = "eeg"
    """Electroencephalography."""

    ELECTRODES: Literal["electrodes"] = "electrodes"
    """Electrodes."""

    EMG: Literal["emg"] = "emg"
    """Electromyography."""

    EPI: Literal["epi"] = "epi"
    """EPI."""

    EVENTS: Literal["events"] = "events"
    """Events."""

    EXPADC: Literal["expADC"] = "expADC"
    """Exponental ADC."""

    FIELDMAP: Literal["fieldmap"] = "fieldmap"
    """Fieldmap."""

    HEADSHAPE: Literal["headshape"] = "headshape"
    """Headshape File."""

    IEEG: Literal["ieeg"] = "ieeg"
    """Intracranial Electroencephalography."""

    INPLANET1: Literal["inplaneT1"] = "inplaneT1"
    """Inplane T1."""

    INPLANET2: Literal["inplaneT2"] = "inplaneT2"
    """Inplane T2."""

    M0SCAN: Literal["m0scan"] = "m0scan"
    """M0 image."""

    MAGNITUDE: Literal["magnitude"] = "magnitude"
    """Magnitude."""

    MAGNITUDE1: Literal["magnitude1"] = "magnitude1"
    """Magnitude."""

    MAGNITUDE2: Literal["magnitude2"] = "magnitude2"
    """Magnitude."""

    MARKERS: Literal["markers"] = "markers"
    """MEG Sensor Coil Positions."""

    MASK: Literal["mask"] = "mask"
    """Binary Mask."""

    MEG: Literal["meg"] = "meg"
    """Magnetoencephalography."""

    MOTION: Literal["motion"] = "motion"
    """Motion."""

    MRSI: Literal["mrsi"] = "mrsi"
    """Magnetic resonance spectroscopy imaging."""

    MRSREF: Literal["mrsref"] = "mrsref"
    """MRS reference acquisition."""

    NIRS: Literal["nirs"] = "nirs"
    """Near Infrared Spectroscopy."""

    NORF: Literal["noRF"] = "noRF"
    """No Radio Frequency Excitation Scan."""

    OPTODES: Literal["optodes"] = "optodes"
    """Optodes."""

    PET: Literal["pet"] = "pet"
    """Positron Emission Tomography."""

    PHASE: Literal["phase"] = "phase"
    """Phase image."""

    PHASE1: Literal["phase1"] = "phase1"
    """Phase."""

    PHASE2: Literal["phase2"] = "phase2"
    """Phase."""

    PHASEDIFF: Literal["phasediff"] = "phasediff"
    """Phase-difference."""

    PHOTO: Literal["photo"] = "photo"
    """Photo File."""

    PHYSIO: Literal["physio"] = "physio"
    """Physiological recording."""

    PHYSIOEVENTS: Literal["physioevents"] = "physioevents"
    """Physiological events and asynchronous data."""

    PROBSEG: Literal["probseg"] = "probseg"
    """Probabilistic Segmentation."""

    SBREF: Literal["sbref"] = "sbref"
    """Single-band reference image."""

    SCANS: Literal["scans"] = "scans"
    """Scans file."""

    SESSIONS: Literal["sessions"] = "sessions"
    """Sessions file."""

    STIM: Literal["stim"] = "stim"
    """Continuous recording."""

    SVS: Literal["svs"] = "svs"
    """Single-voxel spectroscopy."""

    TRACE: Literal["trace"] = "trace"
    """Trace-weighted diffusion image."""

    UCT: Literal["uCT"] = "uCT"
    """Micro-CT."""

    UNLOC: Literal["unloc"] = "unloc"
    """Unlocalized spectroscopy."""


class Modality:
    """BIDS modalities."""

    BEH: Literal["beh"] = "beh"
    """Behavioral experiments."""

    EEG: Literal["eeg"] = "eeg"
    """Electroencephalography."""

    EMG: Literal["emg"] = "emg"
    """Electromyography."""

    IEEG: Literal["ieeg"] = "ieeg"
    """Intracranial Electroencephalography."""

    MEG: Literal["meg"] = "meg"
    """Magnetoencephalography."""

    MICR: Literal["micr"] = "micr"
    """Microscopy."""

    MOTION: Literal["motion"] = "motion"
    """Motion."""

    MRI: Literal["mri"] = "mri"
    """Magnetic Resonance Imaging."""

    MRS: Literal["mrs"] = "mrs"
    """Magnetic Resonance Spectroscopy."""

    NIRS: Literal["nirs"] = "nirs"
    """Near-Infrared Spectroscopy."""

    PET: Literal["pet"] = "pet"
    """Positron Emission Tomography."""


@dataclass(frozen=True)
class BIDSFile:
    """Parsed components of a BIDS filename."""

    entities: dict[str, str]
    """Entity key-value pairs (e.g. ``{"sub": "01", "ses": "pre"}``)."""

    suffix: str
    """File suffix (e.g. ``"T1w"``, ``"bold"``)."""

    extension: str
    """File extension including leading dot (e.g. ``".nii.gz"``)."""


def _format_entity(key: str, val: str | int) -> str:
    """Validate and format a single entity key-value pair."""
    if isinstance(val, int):
        if val < 0:
            raise ValueError(f"Negative index for entity '{key}': {val}")
        return f"{key}-{val}"
    if not _LABEL_RE.fullmatch(val):
        raise ValueError(
            f"Invalid label for entity '{key}': {val!r}. Must match: [0-9a-zA-Z+]+"
        )
    return f"{key}-{val}"


_STANDARD_ENTITIES: frozenset[str] = frozenset(
    {
        "sub",
        "tpl",
        "ses",
        "cohort",
        "sample",
        "task",
        "tracksys",
        "acq",
        "nuc",
        "voi",
        "ce",
        "trc",
        "stain",
        "rec",
        "dir",
        "run",
        "mod",
        "echo",
        "flip",
        "inv",
        "mt",
        "part",
        "proc",
        "hemi",
        "space",
        "split",
        "recording",
        "chunk",
        "atlas",
        "seg",
        "scale",
        "res",
        "den",
        "label",
        "desc",
    }
)


def bids_name(
    *,
    sub: str | None = None,
    tpl: str | None = None,
    ses: str | None = None,
    cohort: str | None = None,
    sample: str | None = None,
    task: str | None = None,
    tracksys: str | None = None,
    acq: str | None = None,
    nuc: str | None = None,
    voi: str | None = None,
    ce: str | None = None,
    trc: str | None = None,
    stain: str | None = None,
    rec: str | None = None,
    dir: str | None = None,
    run: int | None = None,
    mod: str | None = None,
    echo: int | None = None,
    flip: int | None = None,
    inv: int | None = None,
    mt: Literal["on", "off"] | None = None,
    part: Literal["mag", "phase", "real", "imag"] | None = None,
    proc: str | None = None,
    hemi: Literal["L", "R"] | None = None,
    space: str | None = None,
    split: int | None = None,
    recording: str | None = None,
    chunk: int | None = None,
    atlas: str | None = None,
    seg: str | None = None,
    scale: str | None = None,
    res: str | None = None,
    den: str | None = None,
    label: str | None = None,
    desc: str | None = None,
    extra: dict[str, str | int] | None = None,
    suffix: str,
    extension: str,
) -> str:
    """Build a BIDS-compliant filename.

    Entities are ordered per the BIDS specification. Label values
    are validated against the BIDS label pattern. Index values
    must be non-negative integers and are converted to strings.

    Args:
        sub: Subject. A person or animal participating in the study.
        tpl: Template. A standardized space of analysis specified or generated by one or
            more averages of features with respect to which group-level and atlas-
            derived results are provided.
        ses: Session. A logical grouping of neuroimaging and behavioral data consistent
            across subjects.
        cohort: Cohort. A set of subjects sharing one or more common characteristics.
        sample: Sample. A sample pertaining to a subject such as tissue, primary cell or
            cell-free sample.
        task: Task. A set of structured activities performed by the participant.
        tracksys: Tracking System. The tracksys-<label> entity can be used as a key-
            value pair to label *_motion.tsv and *_motion.json files.
        acq: Acquisition. The acq-<label> entity corresponds to a custom label the user
            MAY use to distinguish a different set of parameters used for acquiring the
            same modality.
        nuc: Nucleus. The nuc-<label> entity can be used to distinguish acquisitions
            tuned to detect different nuclei.
        voi: Volume of Interest. The voi-<label> entity can be used to distinguish
            acquisitions localized to different regions.
        ce: Contrast Enhancing Agent. The ce-<label> entity can be used to distinguish
            sequences using different contrast enhanced images.
        trc: Tracer. The trc-<label> entity can be used to distinguish sequences using
            different tracers.
        stain: Stain. The stain-<label> key/pair values can be used to distinguish image
            files from the same sample using different stains or antibodies for contrast
            enhancement.
        rec: Reconstruction. The rec-<label> entity can be used to distinguish different
            reconstruction algorithms (for example, MoCo for the ones using motion
            correction).
        dir: Phase-Encoding Direction. The dir-<label> entity can be set to an arbitrary
            legitimate label (for example, dir-LR or dir-AP) to distinguish different
            phase-encoding directions.
        run: Run. The run-<index> entity is used to distinguish separate data
            acquisitions with the same acquisition parameters and (other) entities.
        mod: Corresponding Modality. The mod-<label> entity corresponds to modality
            label for defacing masks, for example, T1w, inplaneT1, referenced by a
            defacemask image.
        echo: Echo. If files belonging to an entity-linked file collection are acquired
            at different echo times, the echo-<index> entity MUST be used to distinguish
            individual files.
        flip: Flip Angle. If files belonging to an entity-linked file collection are
            acquired at different flip angles, the _flip-<index> entity pair MUST be
            used to distinguish individual files.
        inv: Inversion Time. If files belonging to an entity-linked file collection are
            acquired at different inversion times, the inv-<index> entity MUST be used
            to distinguish individual files.
        mt: Magnetization Transfer. If files belonging to an entity-linked file
            collection are acquired at different magnetization transfer (MT) states, the
            _mt-<label> entity MUST be used to distinguish individual files.
        part: Part. This entity is used to indicate which component of the complex
            representation of the MRI signal is represented in voxel data.
        proc: Processed (on device). The proc label is analogous to rec for MR and
            denotes a variant of a file that was a result of particular processing
            performed on the device.
        hemi: Hemisphere. The hemi-<label> entity indicates which hemibrain is described
            by the file.
        space: Space. The space-<label> entity indicates the coordinate system for
            interpreting spatial coordinates.
        split: Split. In the case of long data recordings that exceed a file size of
            2Gb, .fif files are conventionally split into multiple parts.
        recording: Recording. The recording-<label> entity can be used to distinguish
            continuous recording files.
        chunk: Chunk. The chunk-<index> key/value pair is used to distinguish between
            images of the same physical sample with different fields of view acquired in
            the same imaging experiment.
        atlas: Atlas. The atlas-<label> entity identifies files that are part of, or
            derived from, an atlas.
        seg: Segmentation. The seg-<label> key/value pair corresponds to a custom label
            the user MAY use to distinguish specific partitions of the data space
            (segmentations or parcellations).
        scale: Scale. The scale-<label> key/value pair corresponds to a custom label the
            user MAY use to distinguish segmentations that entail different levels of
            *regional resolution* (scales), often indicated by the number of ROIs.
        res: Resolution. Resolution of regularly sampled N-dimensional data.
        den: Density. Density of non-parametric surfaces.
        label: Label. Tissue-type label, following a prescribed vocabulary.
        desc: Description. When necessary to distinguish two files that do not otherwise
            have a distinguishing entity, the desc-<label> entity SHOULD be used.
        extra: Non-standard entities inserted just before
            ``desc`` (e.g.
            ``{"from": "T1w", "to": "template"}``).
            Values follow the same validation rules as
            standard entities.
        suffix: File suffix (e.g. "T1w", "bold").
        extension: File extension with leading dot
            (e.g. ".nii.gz").

    Returns:
        A BIDS-compliant filename string.

    Raises:
        ValueError: If a label value is invalid or an
            index is negative.
    """
    _entities: list[tuple[str, str | int | None]] = [
        ("sub", sub),
        ("tpl", tpl),
        ("ses", ses),
        ("cohort", cohort),
        ("sample", sample),
        ("task", task),
        ("tracksys", tracksys),
        ("acq", acq),
        ("nuc", nuc),
        ("voi", voi),
        ("ce", ce),
        ("trc", trc),
        ("stain", stain),
        ("rec", rec),
        ("dir", dir),
        ("run", run),
        ("mod", mod),
        ("echo", echo),
        ("flip", flip),
        ("inv", inv),
        ("mt", mt),
        ("part", part),
        ("proc", proc),
        ("hemi", hemi),
        ("space", space),
        ("split", split),
        ("recording", recording),
        ("chunk", chunk),
        ("atlas", atlas),
        ("seg", seg),
        ("scale", scale),
        ("res", res),
        ("den", den),
        ("label", label),
    ]
    parts: list[str] = []
    for _key, _val in _entities:
        if _val is not None:
            parts.append(_format_entity(_key, _val))
    if extra is not None:
        _overlap = set(extra) & _STANDARD_ENTITIES
        if _overlap:
            raise ValueError(
                f"Standard entities passed via extra: {_overlap}. "
                "Use the corresponding keyword argument instead."
            )
        for _key, _val in extra.items():
            parts.append(_format_entity(_key, _val))
    if desc is not None:
        parts.append(_format_entity("desc", desc))
    return "_".join([*parts, suffix]) + extension


def bids_path(
    *,
    sub: str | None = None,
    tpl: str | None = None,
    ses: str | None = None,
    cohort: str | None = None,
    sample: str | None = None,
    task: str | None = None,
    tracksys: str | None = None,
    acq: str | None = None,
    nuc: str | None = None,
    voi: str | None = None,
    ce: str | None = None,
    trc: str | None = None,
    stain: str | None = None,
    rec: str | None = None,
    dir: str | None = None,
    run: int | None = None,
    mod: str | None = None,
    echo: int | None = None,
    flip: int | None = None,
    inv: int | None = None,
    mt: Literal["on", "off"] | None = None,
    part: Literal["mag", "phase", "real", "imag"] | None = None,
    proc: str | None = None,
    hemi: Literal["L", "R"] | None = None,
    space: str | None = None,
    split: int | None = None,
    recording: str | None = None,
    chunk: int | None = None,
    atlas: str | None = None,
    seg: str | None = None,
    scale: str | None = None,
    res: str | None = None,
    den: str | None = None,
    label: str | None = None,
    desc: str | None = None,
    extra: dict[str, str | int] | None = None,
    suffix: str,
    extension: str,
    datatype: str,
) -> PurePath:
    """Build a BIDS-compliant relative path.

    Constructs a path following the BIDS directory convention:
    ``sub-<label>/[ses-<label>/]<datatype>/<filename>``

    Args:
        sub: Subject. A person or animal participating in the study.
        tpl: Template. A standardized space of analysis specified or generated by one or
            more averages of features with respect to which group-level and atlas-
            derived results are provided.
        ses: Session. A logical grouping of neuroimaging and behavioral data consistent
            across subjects.
        cohort: Cohort. A set of subjects sharing one or more common characteristics.
        sample: Sample. A sample pertaining to a subject such as tissue, primary cell or
            cell-free sample.
        task: Task. A set of structured activities performed by the participant.
        tracksys: Tracking System. The tracksys-<label> entity can be used as a key-
            value pair to label *_motion.tsv and *_motion.json files.
        acq: Acquisition. The acq-<label> entity corresponds to a custom label the user
            MAY use to distinguish a different set of parameters used for acquiring the
            same modality.
        nuc: Nucleus. The nuc-<label> entity can be used to distinguish acquisitions
            tuned to detect different nuclei.
        voi: Volume of Interest. The voi-<label> entity can be used to distinguish
            acquisitions localized to different regions.
        ce: Contrast Enhancing Agent. The ce-<label> entity can be used to distinguish
            sequences using different contrast enhanced images.
        trc: Tracer. The trc-<label> entity can be used to distinguish sequences using
            different tracers.
        stain: Stain. The stain-<label> key/pair values can be used to distinguish image
            files from the same sample using different stains or antibodies for contrast
            enhancement.
        rec: Reconstruction. The rec-<label> entity can be used to distinguish different
            reconstruction algorithms (for example, MoCo for the ones using motion
            correction).
        dir: Phase-Encoding Direction. The dir-<label> entity can be set to an arbitrary
            legitimate label (for example, dir-LR or dir-AP) to distinguish different
            phase-encoding directions.
        run: Run. The run-<index> entity is used to distinguish separate data
            acquisitions with the same acquisition parameters and (other) entities.
        mod: Corresponding Modality. The mod-<label> entity corresponds to modality
            label for defacing masks, for example, T1w, inplaneT1, referenced by a
            defacemask image.
        echo: Echo. If files belonging to an entity-linked file collection are acquired
            at different echo times, the echo-<index> entity MUST be used to distinguish
            individual files.
        flip: Flip Angle. If files belonging to an entity-linked file collection are
            acquired at different flip angles, the _flip-<index> entity pair MUST be
            used to distinguish individual files.
        inv: Inversion Time. If files belonging to an entity-linked file collection are
            acquired at different inversion times, the inv-<index> entity MUST be used
            to distinguish individual files.
        mt: Magnetization Transfer. If files belonging to an entity-linked file
            collection are acquired at different magnetization transfer (MT) states, the
            _mt-<label> entity MUST be used to distinguish individual files.
        part: Part. This entity is used to indicate which component of the complex
            representation of the MRI signal is represented in voxel data.
        proc: Processed (on device). The proc label is analogous to rec for MR and
            denotes a variant of a file that was a result of particular processing
            performed on the device.
        hemi: Hemisphere. The hemi-<label> entity indicates which hemibrain is described
            by the file.
        space: Space. The space-<label> entity indicates the coordinate system for
            interpreting spatial coordinates.
        split: Split. In the case of long data recordings that exceed a file size of
            2Gb, .fif files are conventionally split into multiple parts.
        recording: Recording. The recording-<label> entity can be used to distinguish
            continuous recording files.
        chunk: Chunk. The chunk-<index> key/value pair is used to distinguish between
            images of the same physical sample with different fields of view acquired in
            the same imaging experiment.
        atlas: Atlas. The atlas-<label> entity identifies files that are part of, or
            derived from, an atlas.
        seg: Segmentation. The seg-<label> key/value pair corresponds to a custom label
            the user MAY use to distinguish specific partitions of the data space
            (segmentations or parcellations).
        scale: Scale. The scale-<label> key/value pair corresponds to a custom label the
            user MAY use to distinguish segmentations that entail different levels of
            *regional resolution* (scales), often indicated by the number of ROIs.
        res: Resolution. Resolution of regularly sampled N-dimensional data.
        den: Density. Density of non-parametric surfaces.
        label: Label. Tissue-type label, following a prescribed vocabulary.
        desc: Description. When necessary to distinguish two files that do not otherwise
            have a distinguishing entity, the desc-<label> entity SHOULD be used.
        extra: Non-standard entities inserted just before
            ``desc``. See :func:`bids_name` for details.
        suffix: File suffix (e.g. "T1w", "bold").
        extension: File extension with leading dot
            (e.g. ".nii.gz").
        datatype: BIDS datatype directory
            (e.g. "anat", "func").

    Returns:
        A BIDS-compliant relative path.
    """
    filename = bids_name(
        sub=sub,
        tpl=tpl,
        ses=ses,
        cohort=cohort,
        sample=sample,
        task=task,
        tracksys=tracksys,
        acq=acq,
        nuc=nuc,
        voi=voi,
        ce=ce,
        trc=trc,
        stain=stain,
        rec=rec,
        dir=dir,
        run=run,
        mod=mod,
        echo=echo,
        flip=flip,
        inv=inv,
        mt=mt,
        part=part,
        proc=proc,
        hemi=hemi,
        space=space,
        split=split,
        recording=recording,
        chunk=chunk,
        atlas=atlas,
        seg=seg,
        scale=scale,
        res=res,
        den=den,
        label=label,
        desc=desc,
        extra=extra,
        suffix=suffix,
        extension=extension,
    )
    dirs: list[str] = []
    if sub is not None:
        dirs.append(f"sub-{sub}")
    if ses is not None:
        dirs.append(f"ses-{ses}")
    dirs.append(datatype)
    return PurePath(*dirs, filename)


def parse_bids_name(filename: str) -> BIDSFile:
    """Parse a BIDS filename into its components.

    Handles compound extensions (e.g. .nii.gz) and extracts
    all entity key-value pairs, suffix, and extension.

    Args:
        filename: A BIDS-compliant filename
            (without directory path).

    Returns:
        Parsed BIDS file components.
    """
    for ext in _COMPOUND_EXTENSIONS:
        if filename.endswith(ext):
            extension = ext
            stem = filename[: -len(ext)]
            break
    else:
        dot_idx = filename.rfind(".")
        if dot_idx == -1:
            extension = ""
            stem = filename
        else:
            extension = filename[dot_idx:]
            stem = filename[:dot_idx]
    parts = stem.split("_")
    suffix = parts[-1]
    entities: dict[str, str] = {}
    for part in parts[:-1]:
        key, _, value = part.partition("-")
        if value:
            entities[key] = value
    return BIDSFile(entities=entities, suffix=suffix, extension=extension)
