# /// script
# dependencies = ["bidsschematools"]
# requires-python = ">=3.12"
# ///
"""Generate BIDS schema constants, utilities, and tests for the niwrap_helper package.

Reads the BIDS schema via bidsschematools and generates:
  - src/niwrap_helper/bids.py   (constants + build/parse functions)
  - tests/unit/test_bids.py (unit tests)

Run with:
    uv run scripts/generate_bids_tools.py
"""

from __future__ import annotations

import subprocess
import textwrap
from pathlib import Path

from bidsschematools.schema import load_schema

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_MODULE = ROOT / "src" / "niwrap_helper" / "bids.py"
OUTPUT_TESTS = ROOT / "tests" / "test_bids.py"

GENERATED_HEADER = (
    "# Auto-generated by scripts/generate_bids_tools.py — DO NOT EDIT\n"
    "# Regenerate with: uv run scripts/generate_bids_tools.py\n"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def q(s: str) -> str:
    """Double-quote a string for Python source."""
    return f'"{s}"'


def to_const(value: str) -> str:
    """Convert a BIDS value to an UPPER_CASE Python constant name."""
    name = value.upper()
    if name[0].isdigit():
        name = "_" + name
    return name


def clean_desc(desc: str) -> str:
    """Strip Markdown escaping from schema descriptions."""
    return desc.replace("\\*", "*").replace("\\_", "_")


def first_sentence(text: str) -> str:
    """Extract the first sentence from a Markdown description."""
    collapsed = " ".join(text.split())
    collapsed = collapsed.replace("`", "")
    # Find first period followed by space or end-of-string.
    for i, ch in enumerate(collapsed):
        if ch == "." and (i + 1 >= len(collapsed) or collapsed[i + 1] == " "):
            return collapsed[: i + 1]
    return collapsed


def wrap_arg_doc(key: str, desc: str, indent: int = 8) -> list[str]:
    """Wrap an Args docstring entry to fit within 88 columns."""
    prefix = " " * indent + f"{key}: "
    continuation = " " * (indent + 4)
    max_width = 88

    full = prefix + desc
    if len(full) <= max_width:
        return [full]

    # textwrap.fill accounts for indent widths when computing line breaks.
    text = textwrap.fill(
        desc,
        width=max_width,
        initial_indent=prefix,
        subsequent_indent=continuation,
    )
    return text.split("\n")


# ---------------------------------------------------------------------------
# Module generation
# ---------------------------------------------------------------------------


def generate_module(  # noqa: C901
    bids_version: str,
    entities: list[dict[str, object]],
    datatypes: list[tuple[str, str]],
    suffixes: list[tuple[str, str]],
    modalities: list[tuple[str, str]],
    compound_extensions: list[str],
    label_pattern: str,
) -> str:
    """Return the full source of src/niwrap_helper/bids.py."""
    lines: list[str] = []

    def w(s: str = "") -> None:
        lines.append(s)

    # -- File header --
    w(GENERATED_HEADER.rstrip())
    w('"""BIDS schema constants and utilities.')
    w()
    w(f"Auto-generated from BIDS schema v{bids_version}.")
    w("Regenerate with: ``uv run scripts/generate_bids_tools.py``")
    w('"""')
    w()
    w("from __future__ import annotations")
    w()
    w("import re")
    w("from dataclasses import dataclass")
    w("from pathlib import PurePath")
    w("from typing import Literal")
    w()
    w(f'BIDS_VERSION = "{bids_version}"')
    w()

    # -- Internal helpers --
    w(f'_LABEL_RE = re.compile(r"^{label_pattern}$")')
    w()
    ext_items = ", ".join(q(e) for e in compound_extensions)
    w(f"_COMPOUND_EXTENSIONS: tuple[str, ...] = ({ext_items},)")
    w()
    w()

    # -- Datatype namespace --
    w("class Datatype:")
    w('    """BIDS datatypes."""')
    w()
    for value, display in datatypes:
        w(f'    {to_const(value)}: Literal["{value}"] = "{value}"')
        w(f'    """{display}."""')
        w()
    w()

    # -- Suffix namespace --
    w("class Suffix:")
    w('    """BIDS suffixes."""')
    w()
    for value, display in suffixes:
        escaped = display.replace('"', '\\"')
        w(f'    {to_const(value)}: Literal["{value}"] = "{value}"')
        w(f'    """{escaped}."""')
        w()
    w()

    # -- Modality namespace --
    w("class Modality:")
    w('    """BIDS modalities."""')
    w()
    for value, display in modalities:
        w(f'    {to_const(value)}: Literal["{value}"] = "{value}"')
        w(f'    """{display}."""')
        w()
    w()

    # -- BIDSFile --
    w("@dataclass(frozen=True)")
    w("class BIDSFile:")
    w('    """Parsed components of a BIDS filename."""')
    w()
    w("    entities: dict[str, str]")
    w('    """Entity key-value pairs (e.g. ``{"sub": "01", "ses": "pre"}``)."""')
    w()
    w("    suffix: str")
    w('    """File suffix (e.g. ``"T1w"``, ``"bold"``)."""')
    w()
    w("    extension: str")
    w('    """File extension including leading dot (e.g. ``".nii.gz"``)."""')
    w()
    w()

    # -- Internal validation helper --
    w("def _format_entity(key: str, val: str | int) -> str:")
    w('    """Validate and format a single entity key-value pair."""')
    w("    if isinstance(val, int):")
    w("        if val < 0:")
    w("            raise ValueError(")
    w("                f\"Negative index for entity '{key}': {val}\"")
    w("            )")
    w('        return f"{key}-{val}"')
    w("    if not _LABEL_RE.fullmatch(val):")
    w("        raise ValueError(")
    w("            f\"Invalid label for entity '{key}': {val!r}. \"")
    w(f'            "Must match: {label_pattern}"')
    w("        )")
    w('    return f"{key}-{val}"')
    w()
    w()
    # -- Standard entity keys set (for extra-entity validation) --
    entity_keys = [str(e["key"]) for e in entities]
    w("_STANDARD_ENTITIES: frozenset[str] = frozenset({")
    for key in entity_keys:
        w(f'    "{key}",')
    w("})")
    w()
    w()

    # -- Typed parameter list: (key, type_hint, short_description, long_description) --
    params: list[tuple[str, str, str, str]] = []
    for e in entities:
        key = str(e["key"])
        fmt = str(e["format"])
        enum = e["enum"]
        display = str(e["display_name"])
        desc_raw = str(e.get("description") or "")
        sentence = first_sentence(desc_raw) if desc_raw else ""
        long_desc = f"{display}. {sentence}" if sentence else f"{display}."

        if enum is not None:
            lit = "Literal[" + ", ".join(q(str(v)) for v in enum) + "]"  # type: ignore[union-attr,attr-defined]
            hint = f"{lit} | None"
        elif fmt == "index":
            hint = "int | None"
        else:
            hint = "str | None"

        params.append((key, hint, display, long_desc))

    # Split params: everything before desc, then desc separately.
    # Extra (non-standard) entities are inserted just before desc.
    params_before_desc = [p for p in params if p[0] != "desc"]

    # -- bids_name --
    w("def bids_name(")
    w("    *,")
    for key, hint, _, _ in params:
        w(f"    {key}: {hint} = None,")
    w("    extra: dict[str, str | int] | None = None,")
    w("    suffix: str,")
    w("    extension: str,")
    w(") -> str:")
    w('    """Build a BIDS-compliant filename.')
    w()
    w("    Entities are ordered per the BIDS specification. Label values")
    w("    are validated against the BIDS label pattern. Index values")
    w("    must be non-negative integers and are converted to strings.")
    w()
    w("    Args:")
    for key, _, _, long_desc in params:
        for line in wrap_arg_doc(key, long_desc):
            w(line)
    w("        extra: Non-standard entities inserted just before")
    w("            ``desc`` (e.g.")
    w('            ``{"from": "T1w", "to": "template"}``).')
    w("            Values follow the same validation rules as")
    w("            standard entities.")
    w('        suffix: File suffix (e.g. "T1w", "bold").')
    w("        extension: File extension with leading dot")
    w('            (e.g. ".nii.gz").')
    w()
    w("    Returns:")
    w("        A BIDS-compliant filename string.")
    w()
    w("    Raises:")
    w("        ValueError: If a label value is invalid or an")
    w("            index is negative.")
    w('    """')

    # body — standard entities (except desc)
    w("    _entities: list[tuple[str, str | int | None]] = [")
    for key, _, _, _ in params_before_desc:
        w(f'        ("{key}", {key}),')
    w("    ]")
    w("    parts: list[str] = []")
    w("    for _key, _val in _entities:")
    w("        if _val is not None:")
    w("            parts.append(_format_entity(_key, _val))")
    # extra entities (with standard-key guard)
    w("    if extra is not None:")
    w("        _overlap = set(extra) & _STANDARD_ENTITIES")
    w("        if _overlap:")
    w("            raise ValueError(")
    w('                f"Standard entities passed via extra: {_overlap}. "')
    w('                "Use the corresponding keyword argument instead."')
    w("            )")
    w("        for _key, _val in extra.items():")
    w("            parts.append(_format_entity(_key, _val))")
    # desc (always last)
    w("    if desc is not None:")
    w('        parts.append(_format_entity("desc", desc))')
    w('    return "_".join([*parts, suffix]) + extension')
    w()
    w()

    # -- bids_path --
    w("def bids_path(")
    w("    *,")
    for key, hint, _, _ in params:
        w(f"    {key}: {hint} = None,")
    w("    extra: dict[str, str | int] | None = None,")
    w("    suffix: str,")
    w("    extension: str,")
    w("    datatype: str,")
    w(") -> PurePath:")
    w('    """Build a BIDS-compliant relative path.')
    w()
    w("    Constructs a path following the BIDS directory convention:")
    w("    ``sub-<label>/[ses-<label>/]<datatype>/<filename>``")
    w()
    w("    Args:")
    for key, _, _, long_desc in params:
        for line in wrap_arg_doc(key, long_desc):
            w(line)
    w("        extra: Non-standard entities inserted just before")
    w("            ``desc``. See :func:`bids_name` for details.")
    w('        suffix: File suffix (e.g. "T1w", "bold").')
    w("        extension: File extension with leading dot")
    w('            (e.g. ".nii.gz").')
    w("        datatype: BIDS datatype directory")
    w('            (e.g. "anat", "func").')
    w()
    w("    Returns:")
    w("        A BIDS-compliant relative path.")
    w('    """')

    w("    filename = bids_name(")
    for key, _, _, _ in params:
        w(f"        {key}={key},")
    w("        extra=extra,")
    w("        suffix=suffix,")
    w("        extension=extension,")
    w("    )")
    w("    dirs: list[str] = []")
    w("    if sub is not None:")
    w('        dirs.append(f"sub-{sub}")')
    w("    if ses is not None:")
    w('        dirs.append(f"ses-{ses}")')
    w("    dirs.append(datatype)")
    w("    return PurePath(*dirs, filename)")
    w()
    w()

    # -- parse_bids_name --
    w("def parse_bids_name(filename: str) -> BIDSFile:")
    w('    """Parse a BIDS filename into its components.')
    w()
    w("    Handles compound extensions (e.g. .nii.gz) and extracts")
    w("    all entity key-value pairs, suffix, and extension.")
    w()
    w("    Args:")
    w("        filename: A BIDS-compliant filename")
    w("            (without directory path).")
    w()
    w("    Returns:")
    w("        Parsed BIDS file components.")
    w('    """')
    w("    for ext in _COMPOUND_EXTENSIONS:")
    w("        if filename.endswith(ext):")
    w("            extension = ext")
    w("            stem = filename[: -len(ext)]")
    w("            break")
    w("    else:")
    w('        dot_idx = filename.rfind(".")')
    w("        if dot_idx == -1:")
    w('            extension = ""')
    w("            stem = filename")
    w("        else:")
    w("            extension = filename[dot_idx:]")
    w("            stem = filename[:dot_idx]")
    w('    parts = stem.split("_")')
    w("    suffix = parts[-1]")
    w("    entities: dict[str, str] = {}")
    w("    for part in parts[:-1]:")
    w('        key, _, value = part.partition("-")')
    w("        if value:")
    w("            entities[key] = value")
    w("    return BIDSFile(entities=entities, suffix=suffix, extension=extension)")
    w()

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Test generation
# ---------------------------------------------------------------------------


def generate_tests(
    entities: list[dict[str, object]],
    datatypes: list[tuple[str, str]],
    suffixes: list[tuple[str, str]],
    modalities: list[tuple[str, str]],
) -> str:
    """Return the full source of tests/unit/test_bids.py."""
    lines: list[str] = []

    def w(s: str = "") -> None:
        lines.append(s)

    # Pick a few representative entities for test generation.
    enum_entities = [e for e in entities if e["enum"] is not None]

    # Header
    w(GENERATED_HEADER.rstrip())
    w('"""Unit tests for niwrap_helper.bids (auto-generated)."""')
    w()
    w("from pathlib import PurePath")
    w()
    w("import pytest")
    w()
    w("from niwrap_helper.bids import (")
    w("    BIDSFile,")
    w("    Datatype,")
    w("    Modality,")
    w("    Suffix,")
    w("    bids_name,")
    w("    bids_path,")
    w("    parse_bids_name,")
    w(")")
    w()
    w()

    # ---- TestBidsName ----
    w("class TestBidsName:")
    w('    """Tests for bids_name."""')
    w()

    # basic filename
    w("    def test_basic(self) -> None:")
    w('        """Build a simple filename with sub + suffix."""')
    w("        result = bids_name(")
    w('            sub="01", suffix="T1w", extension=".nii.gz"')
    w("        )")
    w('        assert result == "sub-01_T1w.nii.gz"')
    w()

    # multiple entities
    w("    def test_multiple_entities(self) -> None:")
    w('        """Build filename with several entities."""')
    w("        result = bids_name(")
    w('            sub="01",')
    w('            ses="pre",')
    w('            task="rest",')
    w("            run=2,")
    w('            desc="preproc",')
    w('            suffix="bold",')
    w('            extension=".nii.gz",')
    w("        )")
    w("        assert result == (")
    w('            "sub-01_ses-pre_task-rest_run-2_desc-preproc_bold.nii.gz"')
    w("        )")
    w()

    # entity ordering
    w("    def test_entity_ordering(self) -> None:")
    w('        """Entities are ordered per the BIDS spec regardless of kwarg order."""')
    w("        result = bids_name(")
    w('            desc="x", run=1, ses="A", sub="01",')
    w('            suffix="T1w", extension=".nii.gz",')
    w("        )")
    w('        assert result.startswith("sub-01_ses-A_")')
    w('        assert result.endswith("_desc-x_T1w.nii.gz")')
    w()

    # index entities produce bare integers
    w("    def test_index_entity(self) -> None:")
    w('        """Index entities accept int and format without zero-padding."""')
    w("        result = bids_name(")
    w('            sub="01", run=3, suffix="bold", extension=".nii.gz"')
    w("        )")
    w('        assert "run-3" in result')
    w()

    # suffix-only (no entities)
    w("    def test_suffix_only(self) -> None:")
    w('        """When no entities are given, result is just suffix + ext."""')
    w("        result = bids_name(")
    w('            suffix="participants", extension=".tsv"')
    w("        )")
    w('        assert result == "participants.tsv"')
    w()

    # label validation
    w("    def test_invalid_label_raises(self) -> None:")
    w('        """Labels with invalid characters raise ValueError."""')
    w('        with pytest.raises(ValueError, match="Invalid label"):')
    w("            bids_name(")
    w('                sub="bad label!",')
    w('                suffix="T1w",')
    w('                extension=".nii.gz",')
    w("            )")
    w()

    # negative index validation
    w("    def test_negative_index_raises(self) -> None:")
    w('        """Negative index values raise ValueError."""')
    w('        with pytest.raises(ValueError, match="Negative index"):')
    w("            bids_name(")
    w('                sub="01",')
    w("                run=-1,")
    w('                suffix="T1w",')
    w('                extension=".nii.gz",')
    w("            )")
    w()

    # enum entities
    if enum_entities:
        e = enum_entities[0]
        key = str(e["key"])
        val = str(e["enum"][0])  # type: ignore[index]
        w("    def test_enum_entity(self) -> None:")
        w(f'        """Enum entity {key!r} accepts allowed values."""')
        w("        result = bids_name(")
        w(f'            sub="01", {key}="{val}",')
        w('            suffix="T1w", extension=".nii.gz",')
        w("        )")
        w(f'        assert "{key}-{val}" in result')
        w()

    # using Suffix/Datatype constants
    w("    def test_with_suffix_constant(self) -> None:")
    w('        """Suffix constants work as suffix values."""')
    w("        result = bids_name(")
    w('            sub="01", suffix=Suffix.T1W, extension=".nii.gz"')
    w("        )")
    w('        assert result == "sub-01_T1w.nii.gz"')
    w()

    # extra entities
    w("    def test_extra_entities(self) -> None:")
    w('        """Non-standard entities are inserted before desc."""')
    w("        result = bids_name(")
    w('            sub="01",')
    w("            extra={")
    w('                "from": "T1w",')
    w('                "to": "template",')
    w('                "mode": "image",')
    w("            },")
    w('            suffix="xfm",')
    w('            extension=".nii.gz",')
    w("        )")
    w("        assert result == (")
    w('            "sub-01_from-T1w_to-template_mode-image_xfm.nii.gz"')
    w("        )")
    w()

    w("    def test_extra_before_desc(self) -> None:")
    w('        """Extra entities appear after standard ones but before desc."""')
    w("        result = bids_name(")
    w('            sub="01",')
    w('            desc="brain",')
    w('            extra={"from": "T1w", "to": "MNI"},')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("        )")
    w("        assert result == (")
    w('            "sub-01_from-T1w_to-MNI_desc-brain_T1w.nii.gz"')
    w("        )")
    w()

    w("    def test_extra_with_int_value(self) -> None:")
    w('        """Extra entities accept integer values."""')
    w("        result = bids_name(")
    w('            sub="01",')
    w('            extra={"iter": 3},')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("        )")
    w('        assert "iter-3" in result')
    w()

    w("    def test_extra_validation(self) -> None:")
    w('        """Extra entity values are validated."""')
    w('        with pytest.raises(ValueError, match="Invalid label"):')
    w("            bids_name(")
    w('                sub="01",')
    w('                extra={"bad": "not valid!"},')
    w('                suffix="T1w",')
    w('                extension=".nii.gz",')
    w("            )")
    w()

    # standard entity in extra raises
    w("    def test_extra_rejects_standard_entity(self) -> None:")
    w('        """Standard entities passed via extra raise ValueError."""')
    w('        with pytest.raises(ValueError, match="Standard entities"):')
    w("            bids_name(")
    w('                sub="01",')
    w('                extra={"run": 1},')
    w('                suffix="T1w",')
    w('                extension=".nii.gz",')
    w("            )")
    w()
    w()

    # ---- TestBidsPath ----
    w("class TestBidsPath:")
    w('    """Tests for bids_path."""')
    w()

    w("    def test_with_datatype(self) -> None:")
    w('        """Path includes sub/ses/datatype directories."""')
    w("        result = bids_path(")
    w('            sub="01",')
    w('            ses="pre",')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("            datatype=Datatype.ANAT,")
    w("        )")
    w("        expected = PurePath(")
    w('            "sub-01", "ses-pre", "anat",')
    w('            "sub-01_ses-pre_T1w.nii.gz",')
    w("        )")
    w("        assert result == expected")
    w()

    w("    def test_sub_only(self) -> None:")
    w('        """Path with subject but no session."""')
    w("        result = bids_path(")
    w('            sub="01",')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("            datatype=Datatype.ANAT,")
    w("        )")
    w("        expected = PurePath(")
    w('            "sub-01", "anat", "sub-01_T1w.nii.gz"')
    w("        )")
    w("        assert result == expected")
    w()

    w("    def test_returns_purepath(self) -> None:")
    w('        """Return type is PurePath."""')
    w("        result = bids_path(")
    w('            sub="01",')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("            datatype=Datatype.ANAT,")
    w("        )")
    w("        assert isinstance(result, PurePath)")
    w()
    w()

    # ---- TestParseBidsName ----
    w("class TestParseBidsName:")
    w('    """Tests for parse_bids_name."""')
    w()

    w("    def test_basic_parse(self) -> None:")
    w('        """Parse a standard BIDS filename."""')
    w("        result = parse_bids_name(")
    w('            "sub-01_ses-pre_desc-brain_T1w.nii.gz"')
    w("        )")
    w("        assert result == BIDSFile(")
    w('            entities={"sub": "01", "ses": "pre",')
    w('                      "desc": "brain"},')
    w('            suffix="T1w",')
    w('            extension=".nii.gz",')
    w("        )")
    w()

    w("    def test_compound_extension(self) -> None:")
    w('        """Compound extensions like .nii.gz are kept intact."""')
    w("        result = parse_bids_name(")
    w('            "sub-01_bold.nii.gz"')
    w("        )")
    w('        assert result.extension == ".nii.gz"')
    w('        assert result.suffix == "bold"')
    w()

    w("    def test_simple_extension(self) -> None:")
    w('        """Simple extensions are parsed correctly."""')
    w("        result = parse_bids_name(")
    w('            "sub-01_ses-01_scans.tsv"')
    w("        )")
    w('        assert result.extension == ".tsv"')
    w('        assert result.suffix == "scans"')
    w()

    w("    def test_no_extension(self) -> None:")
    w('        """Filenames without extensions are handled."""')
    w('        result = parse_bids_name("sub-01_T1w")')
    w('        assert result.extension == ""')
    w('        assert result.suffix == "T1w"')
    w()

    w("    def test_index_entity_as_string(self) -> None:")
    w('        """Parsed index entities are returned as strings."""')
    w("        result = parse_bids_name(")
    w('            "sub-01_run-2_bold.nii.gz"')
    w("        )")
    w('        assert result.entities["run"] == "2"')
    w()

    w("    def test_round_trip(self) -> None:")
    w('        """Build then parse produces matching components."""')
    w("        name = bids_name(")
    w('            sub="01",')
    w('            ses="pre",')
    w("            run=3,")
    w('            desc="preproc",')
    w('            suffix="bold",')
    w('            extension=".nii.gz",')
    w("        )")
    w("        parsed = parse_bids_name(name)")
    w('        assert parsed.suffix == "bold"')
    w('        assert parsed.extension == ".nii.gz"')
    w('        assert parsed.entities["sub"] == "01"')
    w('        assert parsed.entities["ses"] == "pre"')
    w('        assert parsed.entities["run"] == "3"')
    w('        assert parsed.entities["desc"] == "preproc"')
    w()

    w("    def test_non_standard_entities(self) -> None:")
    w('        """Non-standard entity keys are parsed into entities dict."""')
    w("        result = parse_bids_name(")
    w('            "sub-01_from-T1w_to-template_mode-image_xfm.nii.gz"')
    w("        )")
    w('        assert result.entities["from"] == "T1w"')
    w('        assert result.entities["to"] == "template"')
    w('        assert result.entities["mode"] == "image"')
    w('        assert result.suffix == "xfm"')
    w()
    w()

    # ---- TestConstants ----
    w("class TestConstants:")
    w('    """Tests for namespace constant classes."""')
    w()

    # Spot-check a few datatypes
    w("    def test_datatype_values(self) -> None:")
    w('        """Datatype constants hold the expected string values."""')
    for val, _ in datatypes[:5]:
        w(f'        assert Datatype.{to_const(val)} == "{val}"')
    w()

    # Spot-check a few suffixes
    common_suffixes = [
        (v, d)
        for v, d in suffixes
        if v in ("T1w", "T2w", "bold", "dwi", "mask", "events")
    ]
    w("    def test_suffix_values(self) -> None:")
    w('        """Suffix constants hold the expected string values."""')
    for val, _ in common_suffixes:
        w(f'        assert Suffix.{to_const(val)} == "{val}"')
    w()

    # Spot-check modalities
    w("    def test_modality_values(self) -> None:")
    w('        """Modality constants hold the expected string values."""')
    for val, _ in modalities[:4]:
        w(f'        assert Modality.{to_const(val)} == "{val}"')
    w()

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Generate bids.py and test_bids.py from the BIDS schema."""
    schema = load_schema()
    bids_version: str = schema.bids_version

    # --- Collect schema data ------------------------------------------------

    label_pattern: str = schema.objects.formats.label.pattern
    entity_order_long: list[str] = list(schema.rules.entities)

    entities: list[dict[str, object]] = []
    for long_name in entity_order_long:
        ent = schema.objects.entities[long_name]
        desc_raw = str(ent.description) if hasattr(ent, "description") else ""
        entities.append(
            {
                "key": ent.name,
                "long_name": long_name,
                "display_name": ent.display_name,
                "format": ent.format,
                "enum": tuple(ent.enum) if hasattr(ent, "enum") else None,
                "description": clean_desc(desc_raw),
            }
        )

    datatypes = sorted(
        (dt.value, clean_desc(dt.display_name))
        for dt in schema.objects.datatypes.values()
    )
    suffixes = sorted(
        (suf.value, clean_desc(suf.display_name))
        for suf in schema.objects.suffixes.values()
    )
    modalities = sorted(
        (key, clean_desc(mod.display_name))
        for key, mod in schema.objects.modalities.items()
    )

    all_extensions = sorted(ext.value for ext in schema.objects.extensions.values())
    compound_extensions = sorted(
        (v for v in all_extensions if v.startswith(".") and v[1:].count(".") >= 1),
        key=len,
        reverse=True,
    )

    # --- Generate & write module --------------------------------------------

    module_src = generate_module(
        bids_version=bids_version,
        entities=entities,
        datatypes=datatypes,
        suffixes=suffixes,
        modalities=modalities,
        compound_extensions=compound_extensions,
        label_pattern=label_pattern,
    )
    OUTPUT_MODULE.write_text(module_src, encoding="utf-8")
    print(f"Generated {OUTPUT_MODULE}")  # noqa: T201

    # --- Generate & write tests ---------------------------------------------

    tests_src = generate_tests(
        entities=entities,
        datatypes=datatypes,
        suffixes=suffixes,
        modalities=modalities,
    )
    OUTPUT_TESTS.write_text(tests_src, encoding="utf-8")
    print(f"Generated {OUTPUT_TESTS}")  # noqa: T201

    # --- Format & lint both files -------------------------------------------

    for path in (OUTPUT_MODULE, OUTPUT_TESTS):
        for cmd, label in [
            (["uv", "run", "ruff", "format", str(path)], "ruff format"),
            (
                ["uv", "run", "ruff", "check", "--fix", str(path)],
                "ruff check --fix",
            ),
        ]:
            try:
                subprocess.run(cmd, check=True, capture_output=True)  # noqa: S603
                print(f"  {path.name} {label}: ok")  # noqa: T201
            except (subprocess.CalledProcessError, FileNotFoundError) as exc:
                print(f"  {path.name} {label}: FAILED ({exc})")  # noqa: T201


if __name__ == "__main__":
    main()
